### ISSUE TITLE
现在开源出来的，不方便集成

### ISSUE THREAD

**Issue by AgentEric** [Meiqia/MQChatViewController#94]
非美洽SDK用户集成起来不方便，使用情况不清楚，非美洽 SDK 开发人员必须导入美洽 SDK 文件才能使用

**Comment by ijinmao** [comment]
MQChatConfig.h 当中有个宏，把他注释掉后，代码中的预处理就屏蔽了美洽 SDK 的文件，你可以试一下
`#define INCLUDE_MEIQIA_SDK`

**Comment by xiaya** [comment]
朋友，你们有发送表情和发送文件吗，如果有，你们怎么加到美洽的聊天界面里面的？ 谢谢
